/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.Component;
import java.awt.Window;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import services.IUserServiec;
import services.imp.UserServiec;

/**
 *
 * @author hungh
 */
public class frm_Dangnhap extends javax.swing.JPanel {

    boolean hish = false;
    private IUserServiec userServiec;

    public frm_Dangnhap() {
        initComponents();
        userServiec = new UserServiec();
    }

    public void dangnhap() {
        txtUser.grabFocus();
    }

    public void addEventquenmatkhau(ActionListener event) {
        quenmatkhau1.addActionListener(event);
    }

    public void btndangnhapEven(ActionListener event) {
        myButton2.addActionListener(event);
    }

    public boolean isdangnhap() {
        String TaiKhaon = txtUser.getText().trim();
        String MatKhau = txtPass.getText().trim();
        boolean dangNhap = userServiec.getUser(TaiKhaon, MatKhau);
        return dangNhap;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtPass = new swing.MyPassword();
        jLabel3 = new javax.swing.JLabel();
        myButton1 = new swing.MyButton();
        lbl_thongBao = new javax.swing.JButton();
        txtUser = new swing.MyTextField();
        jLabel1 = new javax.swing.JLabel();
        myButton2 = new swing.MyButton();
        hideshow = new javax.swing.JLabel();
        quenmatkhau1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(328, 373));
        setMinimumSize(new java.awt.Dimension(328, 373));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(328, 373));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Đăng nhập");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 257, 40));

        txtPass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPass.setMinimumSize(new java.awt.Dimension(300, 40));
        txtPass.setPreferredSize(new java.awt.Dimension(300, 40));
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });
        add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 280, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Mật khẩu");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 24));

        myButton1.setBackground(new java.awt.Color(125, 229, 251));
        myButton1.setForeground(new java.awt.Color(0, 51, 102));
        myButton1.setText("Thoát");
        myButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 120, 48));

        lbl_thongBao.setForeground(new java.awt.Color(255, 51, 51));
        lbl_thongBao.setBorder(null);
        lbl_thongBao.setContentAreaFilled(false);
        lbl_thongBao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(lbl_thongBao, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        txtUser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtUser.setMinimumSize(new java.awt.Dimension(300, 40));
        txtUser.setName(""); // NOI18N
        txtUser.setPreferredSize(new java.awt.Dimension(300, 40));
        add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 280, 41));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Tài khoản");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 60, 24));

        myButton2.setBackground(new java.awt.Color(125, 229, 251));
        myButton2.setForeground(new java.awt.Color(0, 51, 102));
        myButton2.setText("Đăng nhập");
        myButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });
        add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 120, 48));

        hideshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hide.png"))); // NOI18N
        hideshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideshowMouseClicked(evt);
            }
        });
        add(hideshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 30, 40));

        quenmatkhau1.setForeground(new java.awt.Color(255, 51, 51));
        quenmatkhau1.setText("Quên mật khẩu ?");
        quenmatkhau1.setBorder(null);
        quenmatkhau1.setContentAreaFilled(false);
        quenmatkhau1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(quenmatkhau1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Bạn Có Chắc Chắn Muốn Thoát Không !") != JOptionPane.YES_OPTION) {
            return;
        }
        System.exit(0);
    }//GEN-LAST:event_myButton1ActionPerformed

    private void hideshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideshowMouseClicked
        if (hish == false) {
            hish = true;
            hideshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hide.png")));
            txtPass.setEchoChar((char) 0);
        } else {
            hish = false;
            hideshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/show.png")));
            txtPass.setEchoChar('\u25cf');
        }

    }//GEN-LAST:event_hideshowMouseClicked

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed

    }//GEN-LAST:event_myButton2ActionPerformed

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (isdangnhap() == true) {
                Component comp = SwingUtilities.getRoot(this);
                ((Window) comp).dispose();
            }
        }
    }//GEN-LAST:event_txtPassKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hideshow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton lbl_thongBao;
    private swing.MyButton myButton1;
    private swing.MyButton myButton2;
    private javax.swing.JButton quenmatkhau1;
    private swing.MyPassword txtPass;
    private swing.MyTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
